export {filter} from './lib/filter.js';
export {i} from './lib/i.js';
export {isPlainObject} from './lib/is-plain-object.js';
export {k} from './lib/k.js';
export {merge} from './lib/merge.js';
export {noop} from './lib/noop.js';
export {pipe} from './lib/pipe.js';
export {prop} from './lib/prop.js';
export {props} from './lib/props.js';
